FROM node:alpine as builder

ENV NODE_ENV production

WORKDIR /client

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.25

COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /client/dist /usr/share/nginx/html

RUN touch /var/run/nginx.pid

RUN chown -R nginx:nginx /var/run/nginx.pid /usr/share/nginx/html /var/cache/nginx /var/log/nginx /etc/nginx/conf.d

USER nginx

CMD ["nginx", "-g", "daemon off;"]