export { default as Indicator } from './Indicator';
export { default as IndicatorDetail } from './IndicatorDetail';
export { default as IndicatorInput } from './IndicatorInput';
export { default as Login } from './Login';
export { default as Profile } from './Profile';
export { default as User } from './User';
export { default as Department } from './Department';
export { default as Major } from './Major';
export { default as NotFound } from './NotFound';
